from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import os
from datetime import datetime

class PDFService:
    def generate_disease_report(self, report, cv_metrics: dict, confusion_spectrum: list) -> str:
        """
        Generates a PDF report for a specific disease case.
        Returns the file path of the generated PDF.
        """
        # Ensure directory exists
        os.makedirs("uploads", exist_ok=True)
        pdf_filename = f"uploads/Report_{report.report_id}.pdf"
        
        c = canvas.Canvas(pdf_filename, pagesize=letter)
        width, height = letter

        # --- HEADER ---
        c.setFont("Helvetica-Bold", 20)
        c.drawString(50, height - 50, "TeaCare Digital Pathology Report")
        
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.gray)
        c.drawString(50, height - 70, "Automated diagnostics generated by TeaCare Research Engine v2.0")
        c.setFillColor(colors.black)

        c.setFont("Helvetica", 12)
        c.drawString(50, height - 100, f"Report ID: #{report.report_id}")
        c.drawString(50, height - 120, f"Date: {report.timestamp}")
        c.drawString(300, height - 100, f"Analyst ID: {report.user_id}")
        
        # Safe access for optional location data
        lat = report.latitude if report.latitude else "N/A"
        lng = report.longitude if report.longitude else "N/A"
        c.drawString(300, height - 120, f"Location: {lat}, {lng}")

        c.setStrokeColor(colors.indigo)
        c.setLineWidth(2)
        c.line(50, height - 140, 550, height - 140)

        # --- SECTION 1: PRIMARY DIAGNOSIS ---
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 170, "1. Primary Diagnosis")
        
        # Box for result
        c.setStrokeColor(colors.black)
        c.setLineWidth(1)
        c.rect(50, height - 230, 500, 50, stroke=1, fill=0)
        
        c.setFont("Helvetica-Bold", 14)
        c.drawString(70, height - 200, f"{report.disease_name}")
        
        c.setFont("Helvetica-Bold", 14)
        c.drawRightString(530, height - 200, f"{report.confidence}")
        c.setFont("Helvetica", 10)
        c.drawRightString(530, height - 215, "Confidence Score")

        # --- SECTION 2: AI CONFUSION SPECTRUM ---
        y_pos = height - 270
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y_pos, "2. AI Confusion Spectrum")
        y_pos -= 25
        
        c.setFont("Helvetica", 10)
        c.drawString(50, y_pos, "Top 5 Candidate Diseases (Probability Distribution):")
        y_pos -= 20

        for item in confusion_spectrum:
            # Draw Bar Background
            c.setFillColor(colors.whitesmoke)
            c.rect(150, y_pos - 8, 300, 10, fill=1, stroke=0)
            
            # Draw Bar Foreground (Probability)
            bar_width = (item["prob"] / 100) * 300
            if item["name"] == report.disease_name:
                c.setFillColor(colors.indigo) # Winner is Indigo
            else:
                c.setFillColor(colors.gray)   # Others are Gray
                
            c.rect(150, y_pos - 8, bar_width, 10, fill=1, stroke=0)
            
            # Text Labels
            c.setFillColor(colors.black)
            c.drawString(50, y_pos, f"{item['name']}")
            c.drawString(460, y_pos, f"{item['prob']:.1f}%")
            
            y_pos -= 20

        # --- SECTION 3: BIO-OPTICAL TELEMETRY ---
        y_pos -= 20
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y_pos, "3. Bio-Optical Telemetry")
        y_pos -= 30

        # Create a grid for metrics
        # Row 1: Infection Stats
        c.setFont("Helvetica-Bold", 10)
        c.drawString(60, y_pos, "Infection Severity")
        c.drawString(200, y_pos, "Lesion Count")
        c.drawString(340, y_pos, "Avg Spot Size")
        
        c.setFont("Helvetica", 12)
        c.drawString(60, y_pos - 15, f"{cv_metrics.get('severity', 0)}%")
        c.drawString(200, y_pos - 15, f"{cv_metrics.get('lesion_count', 0)}")
        c.drawString(340, y_pos - 15, f"{cv_metrics.get('avg_spot_area_px', 0)} px")

        y_pos -= 40
        
        # Row 2: Advanced Morphology
        c.setFont("Helvetica-Bold", 10)
        c.drawString(60, y_pos, "Green Leaf Index (GLI)")
        c.drawString(200, y_pos, "Texture (Contrast)")
        c.drawString(340, y_pos, "Circularity (0-1)")
        
        c.setFont("Helvetica", 12)
        c.drawString(60, y_pos - 15, f"{cv_metrics.get('gli_index', 'N/A')}")
        c.drawString(200, y_pos - 15, f"{cv_metrics.get('texture_contrast', 'N/A')}")
        c.drawString(340, y_pos - 15, f"{cv_metrics.get('avg_circularity', 'N/A')}")

        # --- SECTION 4: VISUAL EVIDENCE ---
        y_pos -= 60
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, y_pos, "4. Visual Evidence")
        
        try:
            # Draw Original
            if report.image_url and os.path.exists(report.image_url):
                c.drawImage(report.image_url, 50, y_pos - 220, width=200, height=200, preserveAspectRatio=True)
                c.setFont("Helvetica", 10)
                c.drawString(50, y_pos - 235, "Fig A: Original Specimen")
            
            # Draw Heatmap (if available)
            heatmap_url = cv_metrics.get('heatmap_url')
            if heatmap_url and os.path.exists(heatmap_url):
                c.drawImage(heatmap_url, 300, y_pos - 220, width=200, height=200, preserveAspectRatio=True)
                c.drawString(300, y_pos - 235, "Fig B: Computer Vision Heatmap")
        except Exception as e:
            print(f"PDF Image Error: {e}")

        # --- FOOTER ---
        c.setFont("Helvetica-Oblique", 8)
        c.drawString(50, 30, f"Generated automatically by TeaCare System on {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        c.drawRightString(550, 30, "Page 1 of 1")

        c.save()
        return pdf_filename

pdf_manager = PDFService()